"""Initial migration

Revision ID: 80a82e71f5f2
Revises: 
Create Date: 2021-08-04 22:54:15.630404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a82e71f5f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_url', sa.String(), nullable=True),
    sa.Column('upc', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ean', sa.String(length=13), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('upc', sa.String(length=12), nullable=True),
    sa.Column('gtin', sa.String(length=14), nullable=True),
    sa.Column('elid', sa.String(length=12), nullable=True),
    sa.Column('description', sa.String(length=515), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('size', sa.String(length=32), nullable=True),
    sa.Column('dimension', sa.String(length=32), nullable=True),
    sa.Column('weight', sa.String(length=16), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('lowest_recorded_price', sa.Float(), nullable=True),
    sa.Column('highest_recorded_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upc')
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('upc', sa.String(), nullable=True),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('list_price', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('shipping', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('updated_t', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_offer',
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_offer')
    op.drop_table('offer')
    op.drop_table('item')
    op.drop_table('error')
    # ### end Alembic commands ###
