"""Added timestamp to Inventory table.

Revision ID: a084b4d2f240
Revises: 36f0f1dd6bdb
Create Date: 2021-08-05 15:50:28.645367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a084b4d2f240'
down_revision = '36f0f1dd6bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'timestamp')
    # ### end Alembic commands ###
